import type {
  Catalog,
  MechConfiguration,
  PartDefinition,
} from "../configuration/types";

const heads = [
  {
    id: "surveyor-head",
    name: "测绘者头部",
    priceCredits: 12_000,
    weight: 2,
    power: 6,
    guard: 2,
    mobility: 8,
    slots: ["head"],
  },
  {
    id: "bulwark-head",
    name: "壁垒头部",
    priceCredits: 17_000,
    weight: 4,
    power: 4,
    guard: 10,
    mobility: -2,
    slots: ["head"],
  },
  {
    id: "halo-head",
    name: "光环头部",
    priceCredits: 22_000,
    weight: 3,
    power: 10,
    guard: 4,
    mobility: 4,
    slots: ["head"],
  },
] as const satisfies readonly PartDefinition[];

const armors = [
  {
    id: "ceramic-shell",
    name: "陶瓷外壳",
    priceCredits: 18_000,
    weight: 4,
    power: 2,
    guard: 12,
    mobility: 0,
    slots: ["armor"],
  },
  {
    id: "reactive-bastion",
    name: "反应式堡垒装甲",
    priceCredits: 32_000,
    weight: 10,
    power: 4,
    guard: 24,
    mobility: -8,
    slots: ["armor"],
    incompatibleChassisIds: ["strider-scout"],
  },
  {
    id: "void-weave",
    name: "虚空编织装甲",
    priceCredits: 28_000,
    weight: 5,
    power: 8,
    guard: 8,
    mobility: 6,
    slots: ["armor"],
  },
] as const satisfies readonly PartDefinition[];

const weapons = [
  {
    id: "arc-blade",
    name: "电弧刃",
    priceCredits: 16_000,
    weight: 3,
    power: 14,
    guard: 2,
    mobility: 4,
    slots: ["leftWeapon", "rightWeapon"],
  },
  {
    id: "aegis-shield",
    name: "神盾",
    priceCredits: 24_000,
    weight: 7,
    power: 2,
    guard: 18,
    mobility: -4,
    slots: ["leftWeapon"],
  },
  {
    id: "drone-rack",
    name: "无人机架",
    priceCredits: 14_000,
    weight: 2,
    power: 10,
    guard: 2,
    mobility: 6,
    slots: ["leftWeapon", "rightWeapon"],
  },
  {
    id: "rail-lance",
    name: "磁轨长枪",
    priceCredits: 36_000,
    weight: 9,
    power: 28,
    guard: 0,
    mobility: -8,
    slots: ["rightWeapon"],
  },
] as const satisfies readonly PartDefinition[];

const rearModules = [
  {
    id: "jump-pack",
    name: "跃迁背包",
    priceCredits: 24_000,
    weight: 5,
    power: 10,
    guard: 11,
    mobility: 10,
    slots: ["rearModule"],
  },
  {
    id: "siege-reactor",
    name: "攻城反应堆",
    priceCredits: 34_000,
    weight: 12,
    power: 18,
    guard: 8,
    mobility: -8,
    slots: ["rearModule"],
    incompatibleChassisIds: ["oracle-frame"],
  },
  {
    id: "field-relay",
    name: "战场中继器",
    priceCredits: 26_000,
    weight: 4,
    power: 8,
    guard: 6,
    mobility: 6,
    slots: ["rearModule"],
  },
] as const satisfies readonly PartDefinition[];

export const catalog = {
  chassis: [
    {
      id: "strider-scout",
      name: "游骑侦察型",
      priceCredits: 100_000,
      weight: 12,
      power: 20,
      guard: 12,
      mobility: 50,
      weightLimit: 32,
    },
    {
      id: "bastion-hauler",
      name: "堡垒运输型",
      priceCredits: 132_000,
      weight: 20,
      power: 24,
      guard: 28,
      mobility: 24,
      weightLimit: 52,
    },
    {
      id: "oracle-frame",
      name: "神谕框架",
      priceCredits: 148_000,
      weight: 15,
      power: 32,
      guard: 16,
      mobility: 38,
      weightLimit: 40,
    },
  ],
  heads,
  armors,
  weapons,
  rearModules,
} as const satisfies Catalog;

export const defaultConfiguration: MechConfiguration = {
  version: 1,
  chassisId: "strider-scout",
  headId: "surveyor-head",
  armorId: "ceramic-shell",
  leftWeaponId: "arc-blade",
  rightWeaponId: "drone-rack",
  rearModuleId: "jump-pack",
  finish: {
    primary: "#7a2f24",
    secondary: "#d8b36a",
    metalness: 0.5,
    roughness: 0.6,
    environment: "foundry",
  },
};
